### PR TITLE
[calligra] Correct Fontconfig variable name.

### PR DESCRIPTION
**Pull request by dcaliste**
Calligra builds ok in SDK with this patch, even with the newest extra-cmake-modules.

@pvuorela

### CODE REVIEW

**Comment by dcaliste** [comment]
As mentioned, they have already fixed this upstream : https://invent.kde.org/office/calligra/-/blob/master/libs/text/CMakeLists.txt#L155

What do you suggest :
* keep the quick pqtch here,
* update to the latest upstream and see if something else breaks.

**Comment by pvuorela** [comment]
I'm ok either way. This should unlock updating ecm so perhaps could be nice getting that out of the way?

**Comment by dcaliste** [comment]
Yes, I think it's easier to accept this patch first and look at upgrading later. Many things have changed and the various patches need to be updated. It will take some time.

**Comment by pvuorela** [comment]
Looks good and seems to build with either ecm. Thanks.

**Pull request merged**
